### ISSUE TITLE
How to use custom icons for Prev and Next buttons?

### ISSUE THREAD

**Issue by antoniogiroz** [cloudeep/vuejs-paginate-next#1]
Hi!

The documentation mentions that we can use prev-text and next-text to customize the HTML, but I can't render a custom icon component.

Any example how can I achieve that?

**Comment by ncperng** [comment]
Thanks for asking. You may try
`      <paginate
        :prevText="'<img src=https://cdn-icons-png.flaticon.com/512/109/109618.png></img>'"
      ></paginate>
`
to directly insert an image to prevText or nextText.

Or set a class with css background-setting to prev-link and next-link. Hope is helps.
